SELECT concat('truncate table public.', table_name, ' restart identity cascade;') FROM information_schema.tables WHERE table_schema = 'public';

truncate table public."transaction" restart identity cascade;
truncate table public.settlement_transactions restart identity cascade;
truncate table public.qr_generates restart identity cascade;
truncate table public.transaction_withdraws restart identity cascade;
truncate table public.commission_calculate_transactions restart identity cascade;
truncate table public.commission_transactions restart identity cascade;
truncate table public.batch_process_withdrawal restart identity cascade;
truncate table public.mapping_order_ids restart identity cascade;
update fund_accounts set balance = 0, available_balance = 0;

-- alter
DROP TABLE rpa_status_processing;

DROP TYPE public."status_rpa";

CREATE TYPE "status_rpa" AS ENUM (
  'AVAILABLE',
  'BUSY',
  'OFFLINE'
);

CREATE TABLE "rpa_status_processing" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "max_seq_no" int,
  "status_rpa" status_rpa,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

INSERT INTO rpa_status_processing (id, max_seq_no, "status_rpa", created_at, updated_at) VALUES(1, 1, 'OFFLINE'::public."status_rpa", '2025-02-21 17:36:56.959', '2025-03-03 12:48:00.673');

ALTER TABLE public."users"
ADD COLUMN is_first_login BOOLEAN DEFAULT TRUE,
ADD COLUMN last_updated_password TIMESTAMP NULL;

ALTER TABLE public."users"
ADD COLUMN two_factor_secret VARCHAR(255) NULL,
ADD COLUMN is_mfa_verification BOOLEAN DEFAULT FALSE,
ADD COLUMN is_mfa_enabled BOOLEAN DEFAULT FALSE;

ALTER TABLE public."applications"
ADD COLUMN verify_account_name BOOLEAN DEFAULT FALSE;

ALTER TABLE public."transaction"
ADD COLUMN transaction_details JSON NULL;

ALTER TABLE public."users"
ADD COLUMN two_factor_secret VARCHAR(255) NULL;

ALTER TABLE public."users"
ADD COLUMN is_mfa_verification BOOLEAN DEFAULT FALSE,
ADD COLUMN is_mfa_enabled BOOLEAN DEFAULT FALSE;

-- alter
DROP TABLE public."rpa_json_participants";
DROP TYPE public."transaction_type";

CREATE TYPE "transaction_type" AS ENUM (
  'DEPOSIT',
  'WITHDRAW',
  'TOPUP',
  'TRANSFER',
  'CONFIRM'
);

ALTER TABLE public."bank_rpa_withdrawal"
ADD COLUMN slave_username varchar(100) NULL,
ADD COLUMN slave_password varchar(100) NULL;

ALTER TABLE public."transaction"
ADD COLUMN remark JSON NULL;

CREATE TYPE "batch_status_scb" AS ENUM (
  'SUCCESS',
  'PARTIALLY_SUCCESS',
  'FAILED',
  'PROCESSING',
  'CREATED'
);

ALTER TABLE public."transaction_withdraws"
ADD COLUMN batch_process_withdrawal_id int;

CREATE TABLE "batch_process_withdrawal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "batch_ref" varchar UNIQUE,
  "count_of_items" int,
  "summary_amount" decimal(20,3) NOT NULL,
  "bank_balance_amount" decimal(20,3),
  "bank_rpa_withdrawal_id" int,
  "batch_status" batch_status_scb,
  "batch_file_name" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

ALTER TABLE "transaction_withdraws" ADD FOREIGN KEY ("batch_process_withdrawal_id") REFERENCES "batch_process_withdrawal" ("id");
ALTER TABLE "batch_process_withdrawal" ADD FOREIGN KEY ("bank_rpa_withdrawal_id") REFERENCES "bank_rpa_withdrawal" ("id");

ALTER TABLE public."batch_process_withdrawal"
ADD COLUMN retry int DEFAULT 0,
ADD COLUMN is_pause BOOLEAN DEFAULT FALSE;

ALTER TABLE public."mapping_order_ids"
ADD COLUMN troubleshoot varchar(255) NULL;

ALTER TYPE public."batch_status_scb"
ADD VALUE 'BANK_TRANSFERRED';

ALTER TABLE public."transaction"
ADD COLUMN "customer_balance" decimal(20,3),
ADD COLUMN "customer_id" int;

ALTER TYPE public."transaction_status"
ADD VALUE 'DRAFT';

ALTER TABLE public."mapping_order_ids"
ADD COLUMN signature_key varchar UNIQUE;