version: '3'
services:
  minio-service:
    image: minio/minio
    container_name: minio-container
    command: server /data --console-address ":9090"
    ports: 
      - '9000:9000'
      - '9090:9090'
    volumes: 
      - ./minio:/data
    environment:
      - "MINIO_ROOT_USER=root"
      - "MINIO_ROOT_PASSWORD=password"
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
  mc-service:
    image: minio/mc
    depends_on:
      minio-service:
        condition: service_healthy
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio-container:9000 root password;
      /usr/bin/mc mb myminio/qr-code;
      /usr/bin/mc anonymous set public myminio/qr-code;
      exit 0;
      "
    networks:
      - minio_network

networks:
  minio_network:
    driver: bridge